---
# Per environment values which override defaults in hmpps-prisoner-property-ui/values.yaml

generic-service:
  ingress:
    host: prisoner-property-ui.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://prisoner-property-ui.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    PRISONER_PROPERTY_API_URL: 'https://prisoner-property-api.hmpps.service.justice.gov.uk'
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  alertSeverity: move-a-prisoner-alerts-prod
